(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)
Clear[Afun,AfundT];Afun[T_,\[CapitalDelta]T_,\[Xi]max_]:=Sqrt[((T-1)/\[CapitalDelta]T)^2+1/(\[Xi]max^4)];


(* ::Input::Initialization:: *)
AfundT[T_,\[CapitalDelta]T_,\[Xi]max_]:=(-1+T)/(\[CapitalDelta]T^2 Sqrt[(-1+T)^2/\[CapitalDelta]T^2+1/\[Xi]max^4]);


(* ::Input::Initialization:: *)
AfundT2[T_,\[CapitalDelta]T_,\[Xi]max_]:=1/(Sqrt[(-1+T)^2/\[CapitalDelta]T^2+1/\[Xi]max^4] (\[CapitalDelta]T^2+(-1+T)^2 \[Xi]max^4));


(* ::Input::Initialization:: *)
Clear[cVcrit];cVcrit[T_,\[CapitalDelta]T_,\[Xi]max_]:=(1/(8\[Pi]))(1/\[CapitalDelta]T)^2 1/(Afun[T,\[CapitalDelta]T,\[Xi]max])^(1/2);


(* ::Input::Initialization:: *)
Clear[cVcritdT];cVcritdT[T_,\[CapitalDelta]T_,\[Xi]max_]:=-((-1+T)/(16 \[Pi] \[CapitalDelta]T^4 ((-1+T)^2/\[CapitalDelta]T^2+1/\[Xi]max^4)^(5/4)));


(* ::Input::Initialization:: *)
Afund\[Epsilon][T_,\[CapitalDelta]T_,\[Xi]max_]:=AfundT[T,\[CapitalDelta]T,\[Xi]max]/cVcrit[T,\[CapitalDelta]T,\[Xi]max];
Afund\[Epsilon]2[T_,\[CapitalDelta]T_,\[Xi]max_]:=AfundT2[T,\[CapitalDelta]T,\[Xi]max]/cVcrit[T,\[CapitalDelta]T,\[Xi]max]-AfundT[T,\[CapitalDelta]T,\[Xi]max]*cVcritdT[T,\[CapitalDelta]T,\[Xi]max]/cVcrit[T,\[CapitalDelta]T,\[Xi]max]^2;


(* ::Input::Initialization:: *)
Clear[cVHigh,cVHighdT];cVHigh[T_,aH_]:=aH/3 T^3;cVHighdT[T_,aH_]:=aH T^2;


(* ::Input::Initialization:: *)
Clear[cVQGP,dTcVQGP,\[Epsilon]QGP,pQGP,sQGP,cs2QGP];
cVQGP[T_]:=12 (32+21Nf)/180 T^3;Nf=2;
dTcVQGP[T_]:=36 (32+21Nf)/180 T^2;
\[Epsilon]QGP[T_]:=3 (32+21Nf)/180 T^4;pQGP[T_]:=(32+21Nf)/180 T^4;sQGP[T_]:=4 (32+21Nf)/180 T^3;cs2QGP[T_]:=1/3;


(* ::Input::Initialization:: *)
cVLow[T_,aL_]:=aL/3 T^3;cVLowdT[T_,aL_]:=aL T^2;


(* ::Input::Initialization:: *)
Clear[cVcritFull,cVcritdTFull];


(* ::Input::Initialization:: *)
cVcritdTFull[T_,\[CapitalDelta]T_,\[Xi]max_,c1_,c2_,c3_]:=cVcritdT[T,\[CapitalDelta]T,\[Xi]max]+c1+c2(T-1)+c3 (T-1)^2;


(* ::Input::Initialization:: *)
cVcritFull[T_,\[CapitalDelta]T_,\[Xi]max_,c0_,c1_,c2_,c3_]:=cVcrit[T,\[CapitalDelta]T,\[Xi]max]+c0+c1(T-1)+c2/2 (T-1)^2+c3/3 (T-1)^3;


(* ::Input::Initialization:: *)
Clear[c0Now,c1Now,c2Now,c3Now];{c0Now,c1Now,c2Now,c3Now}={c0,c1,c2,c3}/.First[NSolve[{cVLowdT[TLow,aL]==cVcritdTFull[TLow,\[CapitalDelta]T,\[Xi]max,c1,c2,c3],cVHighdT[THigh,aH]==cVcritdTFull[THigh,\[CapitalDelta]T,\[Xi]max,c1,c2,c3],cVLow[TLow,aL]==cVcritFull[TLow,\[CapitalDelta]T,\[Xi]max,c0,c1,c2,c3],cVHigh[THigh,aH]==cVcritFull[THigh,\[CapitalDelta]T,\[Xi]max,c0,c1,c2,c3]},{c0,c1,c2,c3}]]


(* ::Input::Initialization:: *)
Clear[cVfun,cVLowNow,cVHighNow];cVfun[T_]:=Piecewise[{{cVLow[T,aL],T<= TLow}(*T<Subscript[T, L]*),{cVcritFull[T,\[CapitalDelta]T,\[Xi]max,c0Now,c1Now,c2Now,c3Now],T>= TLow&&T<THigh},(*Subscript[T, L]<T<THigh*){cVHigh[T,aH],T>=  THigh}}];cVLowNow[T_]:=cVLow[T,aL];cVHighNow[T_]:=cVHigh[T,aH];


(* ::Input::Initialization:: *)
Clear[\[Epsilon]Full,sFull,pFull,cs2Full]


(* ::Input::Initialization:: *)
\[Epsilon]Full[T_]:=NIntegrate[cVfun[T1],{T1,0.00001,T}];
sFull[T_]:=NIntegrate[cVfun[T1]/T1,{T1,0.00001,T}];
pFull[T_]:=sFull[T]T-\[Epsilon]Full[T];
cs2Full[T_]:=sFull[T]/cVfun[T];


(* ::Input::Initialization:: *)
ALowFun[T_,d0_,d2_]:=d0+d2/2 (\[Epsilon]Full[T])^2;
ALowFund\[Epsilon][T_,d0_,d2_]:=d2(\[Epsilon]Full[T]);
ALowFund\[Epsilon]2[T_,d0_,d2_]:=d2;


(* ::Input::Initialization:: *)
Clear[d0Now,d2Now,ALow]


(* ::Input::Initialization:: *)
{d0Now,d2Now}={d0,d2}/.First[NSolve[{AfundT[TLow,\[CapitalDelta]T,\[Xi]max](1/cVfun[TLow])==d2 \[Epsilon]Full[TLow],ALowFun[TLow,d0,d2]==Afun[TLow,\[CapitalDelta]T,\[Xi]max]},{d0,d2}]];


(* ::Input::Initialization:: *)
ALow[T_]:=ALowFun[T,d0Now,d2Now];
ALowd\[Epsilon][T_]:=ALowFund\[Epsilon][T,d0Now,d2Now];
ALowd\[Epsilon]2[T_]:=ALowFund\[Epsilon]2[T,d0Now,d2Now];


(* ::Input::Initialization:: *)
Clear[AfunFull];AfunFull[T_]:=Piecewise[{{ALow[T],T<TLow},{Afun[T,\[CapitalDelta]T0,\[Xi]maxnow],T>= TLow}}];
AfunFulld\[Epsilon][T_]:=Piecewise[{{ALowd\[Epsilon][T],T<TLow},{Afund\[Epsilon][T,\[CapitalDelta]T0,\[Xi]maxnow],T>= TLow}}];
AfunFulld\[Epsilon]2[T_]:=Piecewise[{{ALowd\[Epsilon]2[T],T<TLow},{Afund\[Epsilon]2[T,\[CapitalDelta]T0,\[Xi]maxnow],T>= TLow}}];


(* ::Input::Initialization:: *)
Clear[cVPlot,\[Epsilon]Plot,pPlot,sPlot,cs2Plot];


(* ::Input::Initialization:: *)
cVPlot=Show[Plot[{cVfun[T]},{T,0.01,1.5},PlotRange->All,PlotStyle->colorlist,Frame->True,Axes->False,(*PlotLegends\[Rule]Placed[{ShowText["Subscript[c, V,crit,Full]"],ShowText["Subscript[c, V,crit ]"]},{0.2,0.75}],*)FrameLabel->{ShowText["T/\!\(\*SubscriptBox[\(T\), \(c\)]\)"],ShowText["\!\(\*SubscriptBox[\(c\), \(V, crit\)]\)"]},GridLines->{{TLow,THigh}, None}, GridLinesStyle->Directive[Gray, Dashed],PlotLabel->ShowText["\!\(\*SubscriptBox[\(\[Xi]\), \(max\)]\)="<>ToString[\[Xi]max]<>"    \[CapitalDelta]T=0.2;        \!\(\*SubscriptBox[\(T\), \(Low\)]\)="<>ToString[TLow]<>"   \!\(\*SubscriptBox[\(T\), \(High\)]\)="<>ToString[THigh]]],Plot[{cVLowNow[T]},{T,0.01,1.2},PlotRange->All,PlotStyle->colorlist[[2]],Frame->True,Axes->False],Plot[{cVHighNow[T]},{T,0.8,1.5},PlotRange->All,PlotStyle->colorlist[[3]],Frame->True,Axes->False]];


(* ::Input::Initialization:: *)
\[Epsilon]Plot=Plot[{\[Epsilon]Full[T],\[Epsilon]QGP[T]},{T,0.01,2},PlotRange->All,PlotStyle->colorlist,Frame->True,Axes->False,PlotLegends->Placed[{ShowText["with C.P."],ShowText["QGP"]},{0.2,0.55}],GridLines->{{TLow,THigh}, None}, GridLinesStyle->Directive[Gray, Dashed],FrameLabel->{ShowText["T/\!\(\*SubscriptBox[\(T\), \(c\)]\)"],ShowText["\[Epsilon]/\!\(\*SuperscriptBox[SubscriptBox[\(T\), \(c\)], \(4\)]\)"]},PlotLabel->ShowText["\!\(\*SubscriptBox[\(\[Xi]\), \(max\)]\)="<>ToString[\[Xi]max]<>"    \[CapitalDelta]T="<>ToString[\[CapitalDelta]T]]];


(* ::Input::Initialization:: *)
sPlot=Plot[{sFull[T],sQGP[T]},{T,0.01,2},PlotRange->All,PlotStyle->colorlist,Frame->True,Axes->False,PlotLegends->Placed[{ShowText["with C.P."],ShowText["QGP"]},{0.2,0.55}],GridLines->{{TLow,THigh}, None}, GridLinesStyle->Directive[Gray, Dashed],FrameLabel->{ShowText["T/\!\(\*SubscriptBox[\(T\), \(c\)]\)"],ShowText["s/\!\(\*SuperscriptBox[SubscriptBox[\(T\), \(c\)], \(3\)]\)"]},PlotLabel->ShowText["\!\(\*SubscriptBox[\(\[Xi]\), \(max\)]\)="<>ToString[\[Xi]max]<>"    \[CapitalDelta]T="<>ToString[\[CapitalDelta]T]]];


(* ::Input::Initialization:: *)
pPlot=Plot[{pFull[T],pQGP[T]},{T,0.01,2},PlotRange->All,PlotStyle->colorlist,Frame->True,Axes->False,PlotLegends->Placed[{ShowText["with C.P."],ShowText["QGP"]},{0.2,0.55}],GridLines->{{TLow,THigh}, None}, GridLinesStyle->Directive[Gray, Dashed],FrameLabel->{ShowText["T/\!\(\*SubscriptBox[\(T\), \(c\)]\)"],ShowText["p/\!\(\*SuperscriptBox[SubscriptBox[\(T\), \(c\)], \(4\)]\)"]},PlotLabel->ShowText["\!\(\*SubscriptBox[\(\[Xi]\), \(max\)]\)="<>ToString[\[Xi]max]<>"    \[CapitalDelta]T="<>ToString[\[CapitalDelta]T]]];


(* ::Input::Initialization:: *)
cs2Plot=Plot[{cs2Full[T],cs2QGP[T]},{T,0.01,2.5},PlotRange->All,PlotStyle->colorlist,Frame->True,Axes->False,GridLines->{{TLow,THigh}, None}, GridLinesStyle->Directive[Gray, Dashed],PlotLegends->Placed[{ShowText["with C.P."],ShowText["QGP"]},{0.2,0.55}],FrameLabel->{ShowText["T/\!\(\*SubscriptBox[\(T\), \(c\)]\)"],ShowText["\!\(\*SubscriptBox[SuperscriptBox[\(c\), \(2\)], \(s\)]\)"]},PlotLabel->ShowText["\!\(\*SubscriptBox[\(\[Xi]\), \(max\)]\)="<>ToString[\[Xi]max]<>"    \[CapitalDelta]T="<>ToString[\[CapitalDelta]T]]];


(* ::Input::Initialization:: *)
Clear[\[Xi]Plot];\[Xi]Plot=Plot[{(AfunFull[T])^(-1/2),(Afun[T,\[CapitalDelta]T,\[Xi]max])^(-1/2)},{T,0.001,2},PlotRange->All,PlotStyle->colorlist,Frame->True,Axes->False,GridLines->{{TLow,THigh}, None}, GridLinesStyle->Directive[Gray, Dashed],PlotLabel->ShowText["\!\(\*SubscriptBox[\(\[Xi]\), \(max\)]\)="<>ToString[\[Xi]max]],FrameLabel->{ShowText["T/\!\(\*SubscriptBox[\(T\), \(c\)]\)"],ShowText["\[Xi] \!\(\*SubscriptBox[\(T\), \(c\)]\)"]}];
