(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)
colorlistS={{Red,Thick},{Blue,Thick},{Orange,Thick},{Purple,Thick}};
colorlist={{Red,Thick},{Blue,Thick,Dashed},{Orange,Thick,Dotted}};
colorlistDashed={{Red,Thick,Dashed},{Blue,Thick,Dashed},{Orange,Thick,Dashed},{Purple,Thick,Dashed}};
colorlistDotted={{Red,Thick,Dotted},{Blue,Thick,Dotted},{Orange,Thick,Dotted},{Purple,Thick,Dotted}};colorlistDotDashed={{Red,Thick,DotDashed},{Blue,Thick,DotDashed},{Orange,Thick,DotDashed},{Purple,Thick,DotDashed}};


(* ::Input::Initialization:: *)
labelsize={Medium,16};


(* ::Input::Initialization:: *)
rlabel=Text[Style["r (fm)",labelsize]];\[Epsilon]label=Text[Style["\[Epsilon](\!\(\*SuperscriptBox[\(GeV\), \(4\)]\))",labelsize]];vlabel=Text[Style["\!\(\*SubscriptBox[\(v\), \(r\)]\)",labelsize]];


(* ::Input::Initialization:: *)
qperplabel=Text[Style["\!\(\*SubscriptBox[\(q\), \(\[Perpendicular]\)]\)/T ",labelsize]];
dPd\[Omega]label=ShowText["\!\(\*FractionBox[\(1\), \((\[CapitalDelta]\[Tau])\)]\)\!\(\*FractionBox[\(dP\), \(d\[Omega]\)]\)"];
dPd\[Theta]label=ShowText["\!\(\*FractionBox[\(dP\), \(d\[Theta]\)]\)"];(*dPd\[Theta]Ratelabel=ShowText["(dP/d\[Theta])/(g^4L T)"];*)dPd\[Theta]Ratelabel=ShowText["(dP/d\[Theta])/\[Kappa]"];dPd\[Theta]dpRatelabel=ShowText["(\!\(\*SuperscriptBox[\(d\), \(2\)]\)P/d\[Theta] dp)/\[Kappa]"];dPdqRatelabel=(*ShowText["T/(Subscript[p, i] cos\[Theta])(dP/d\[Theta])/(g^4L T)"]*)ShowText["\!\(\*SuperscriptBox[\(10\), \(4\)]\)\[Times][dP/d(\!\(\*SubscriptBox[\(q\), \(\[Perpendicular]\)]\)/T)]/(\!\(\*SuperscriptBox[\(g\), \(4\)]\)L T) "];
pflabel=Text[Style["\!\(\*SubscriptBox[\(p\), \(f\)]\)(GeV) ",labelsize]];
pfdifflabel=Text[Style["(\!\(\*SubscriptBox[\(p\), \(i\)]\)-\!\(\*SubscriptBox[\(p\), \(f\)]\))(GeV) ",labelsize]];
\[Theta]label=Text[Style["\[Theta] (rad)",labelsize]];
plabel=Text[Style["p/T",labelsize]];
(*pfoverpilabel=Text[Style["Subscript[p, f]/Subscript[p, i]",labelsize]];*)


Plabel=Text[Style["P(\[Theta])/\!\(\*SubscriptBox[\(\[Rho]\), \(i\)]\)",labelsize]];
P\[Theta]label=Text[Style["sin(\[Theta]) P(\[Theta])/(\!\(\*SubscriptBox[\(\[Rho]\), \(i\)]\) T \!\(\*SubscriptBox[\(p\), \(i\)]\))",labelsize]];
\[Theta]minlabel=Text[Style["\!\(\*SubscriptBox[\(\[Theta]\), \(min\)]\) (rad)",labelsize]];


(* ::Input::Initialization:: *)
Clear[ShowText];ShowText[A_]:=Text[Style[A,labelsize]];
